version: "3.0"

services:
  app:
    build: .
    command: npm run start:prod
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    restart: always
  db:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
